id: P000646
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W389
  title: ཐོག་མར་བློ་སྦྱོང་ཆོས་ཀྱི་སྒོ་འབྱེད།
  author: ''
  volumes:
    3700e1a2e01c42d591283e8c017e4d01:
      image_group_id: I1KG8865
      title: ''
      volume_number: 1
      total_pages: 140
