id: I452A4842
legacy_id: P000646
ocr_import_info:
  bdrc_scan_id: W389
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T16:17:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T12:14:24.014714+00:00'
last_modified: 2022-09-03 20:14:31.059098
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W389
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW389
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐོག་མར་བློ་སྦྱོང་ཆོས་ཀྱི་སྒོ་འབྱེད།
  author: སྤྱན་སྔ་བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.6987566041388966
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1KG8865:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8865
      total_pages: 140
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8865.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6987566041388966
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
