id: I452A4842
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:18:44+00:00'
last_modified: '2022-06-07T12:32:56.305379+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W389
  title: ཐོག་མར་བློ་སྦྱོང་ཆོས་ཀྱི་སྒོ་འབྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8E0B:
      image_group_id: I1KG8865
      title: ''
      total_pages: 140
      order: 1
      base_file: 8E0B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
